import { NonConformita } from "./types";

export const SEED_NON_CONFORMITA: NonConformita[] = [
  {
    id: "nc-1",
    commessa: "COM-2601",
    cliente: "Ferrari S.p.A.",
    codice_disegno: "DIS-7721-A",
    tipo_nc: "Interna",
    data_apertura: "2026-01-12",
    data_chiusura: "2026-01-14",
    reparto: "CNC",
    causa: "Errore di programmazione CAM",
    costo: 350.00,
    persona: "Davide Rossi",
    responsabile: "Ing. Giorgio Verdi",
    note: "Errore di interpretazione dell'offset dell'asse Z nel software CAM.",
    correzione: "Correzione firmware post-processor ed azzeramento asse Z in macchina.",
    azione_correttiva: "Inserimento di una procedura di simulazione digitale anticollisione su Vericut obbligatoria prima del caricamento pezzo.",
    verifica_efficacia: "NO" // No = non si è ripetuto, quindi efficace
  },
  {
    id: "nc-2",
    commessa: "COM-2598",
    cliente: "Ducati Motor",
    codice_disegno: "DIS-4411-C",
    tipo_nc: "Cliente",
    data_apertura: "2026-01-20",
    data_chiusura: "2026-01-25",
    reparto: "Collaudo",
    causa: "Errore operatore",
    costo: 1200.00,
    persona: "Marco Bianchi",
    responsabile: "Dr. Stefano Russo",
    note: "L'operatore ha saltato la calibrazione finale durante il collaudo del pezzo.",
    correzione: "Rilavorazione del pezzo con ri-taratura software e ripetizione del collaudo con testimone del QA manager.",
    azione_correttiva: "Sviluppo di una check-list digitale bloccante all'interno del terminale operatore.",
    verifica_efficacia: "NO" // No = non si è ripetuto
  },
  {
    id: "nc-3",
    commessa: "COM-2605",
    cliente: "Brembo",
    codice_disegno: "DIS-2309-B",
    tipo_nc: "Interna",
    data_apertura: "2026-02-05",
    data_chiusura: "2026-02-06",
    reparto: "Taglio",
    causa: "Usura utensile",
    costo: 180.00,
    persona: "Luigi Ferrari",
    responsabile: "Mario Grassi",
    note: "La taglierina ha sbeccato il bordo perché l'inserto era a fine ciclo di vita.",
    correzione: "Sostituzione inserto taglierina ed eliminazione sbavature con levigatura manuale sul lotto interessato.",
    azione_correttiva: "Implementato conta-pezzi software con blocco macchina automatico a 500 tagli.",
    verifica_efficacia: "SI" // Sì = si è ripetuto, azione non del tutto efficace
  },
  {
    id: "nc-4",
    commessa: "COM-2612",
    cliente: "Maserati",
    codice_disegno: "DIS-9088-K",
    tipo_nc: "Fornitore",
    data_apertura: "2026-02-18",
    data_chiusura: "2026-02-22",
    reparto: "Collaudo",
    causa: "Materiale grezzo difettoso",
    costo: 950.00,
    persona: "Nino Neri",
    responsabile: "Dr. Stefano Russo",
    note: "Microfratture rilevate sulla superficie del blocco d'alluminio fornito."
  },
  {
    id: "nc-5",
    commessa: "COM-2615",
    cliente: "Lamborghini",
    codice_disegno: "DIS-5440-S",
    tipo_nc: "Interna",
    data_apertura: "2026-03-02",
    data_chiusura: "2026-03-05",
    reparto: "CNC",
    causa: "Errore di programmazione CAM",
    costo: 500.00,
    persona: "Davide Rossi",
    responsabile: "Ing. Giorgio Verdi",
    note: "Codice post-processor non aggiornato per la nuova macchina a 5 assi."
  },
  {
    id: "nc-6",
    commessa: "COM-2620",
    cliente: "Ansaldo Energia",
    codice_disegno: "DIS-1122-F",
    tipo_nc: "Cliente",
    data_apertura: "2026-03-15",
    data_chiusura: "2026-03-24",
    reparto: "Ufficio T.",
    causa: "Specifiche disegno errate",
    costo: 2400.00,
    persona: "Alba Gallo",
    responsabile: "Ing. Elena Fontana",
    note: "L'ufficio tecnico ha invertito tolleranze ISO H7/g6 sul disegno costruttivo."
  },
  {
    id: "nc-7",
    commessa: "COM-2622",
    cliente: "Same Tractors",
    codice_disegno: "DIS-8800-R",
    tipo_nc: "Interna",
    data_apertura: "2026-04-08",
    data_chiusura: "2026-04-09",
    reparto: "CNC",
    causa: "Usura utensile",
    costo: 320.00,
    persona: "Filippo Rizzo",
    responsabile: "Ing. Giorgio Verdi",
    note: "La punta per foratura profonda si è spezzata a causa dell'usura e scarsa refrigerazione."
  },
  {
    id: "nc-8",
    commessa: "COM-2630",
    cliente: "Ducati Motor",
    codice_disegno: "DIS-4412-A",
    tipo_nc: "Interna",
    data_apertura: "2026-04-14",
    data_chiusura: "2026-04-16",
    reparto: "Montaggio",
    causa: "Errore operatore",
    costo: 450.00,
    persona: "Sara Gatti",
    responsabile: "Carlo Parodi",
    note: "Errore di serraggio bulloni carter frizione avvenuto per distrazione."
  },
  {
    id: "nc-9",
    commessa: "COM-2635",
    cliente: "Brembo",
    codice_disegno: "DIS-2311-D",
    tipo_nc: "Interna",
    data_apertura: "2026-05-10",
    data_chiusura: "2026-05-12",
    reparto: "CNC",
    causa: "Errore operatore",
    costo: 850.00,
    persona: "Andrea Moretti",
    responsabile: "Ing. Giorgio Verdi",
    note: "Impostati avanzamenti e giri al minuto errati sulla consolle del tornio CNC."
  },
  {
    id: "nc-10",
    commessa: "COM-2640",
    cliente: "Ferrari S.p.A.",
    codice_disegno: "DIS-7722-H",
    tipo_nc: "Cliente",
    data_apertura: "2026-05-18",
    data_chiusura: "2026-05-25",
    reparto: "Collaudo",
    causa: "Materiale grezzo difettoso",
    costo: 3100.00,
    persona: "Marco Bianchi",
    responsabile: "Dr. Stefano Russo",
    note: "Fusione in lega leggera difettosa con micro-porosità interna visibile ai raggi X."
  },
  {
    id: "nc-11",
    commessa: "COM-2642",
    cliente: "Dallara Automobili",
    codice_disegno: "DIS-3091-E",
    tipo_nc: "Fornitore",
    data_apertura: "2026-05-20",
    data_chiusura: "2026-05-23",
    reparto: "Piegatura",
    causa: "Materiale grezzo difettoso",
    costo: 480.00,
    persona: "Luca Esposito",
    responsabile: "Mario Grassi",
    note: "Scuri metallici arrivati con spessore inferiore del 10% rispetto alle specifiche di ordini."
  },
  {
    id: "nc-12",
    commessa: "COM-2650",
    cliente: "Lamborghini",
    codice_disegno: "DIS-5441-A",
    tipo_nc: "Interna",
    data_apertura: "2026-06-02",
    data_chiusura: "2026-06-03",
    reparto: "Taglio",
    causa: "Usura utensile",
    costo: 220.00,
    persona: "Luigi Ferrari",
    responsabile: "Mario Grassi",
    note: "Deformazione da serraggio eccessivo morsa a causa di usura arresti di battuta."
  },
  {
    id: "nc-13",
    commessa: "COM-2655",
    cliente: "Same Tractors",
    codice_disegno: "DIS-8805-X",
    tipo_nc: "Interna",
    data_apertura: "2026-06-05",
    data_chiusura: "",
    reparto: "Ufficio T.",
    causa: "Specifiche disegno errate",
    costo: 0.00,
    persona: "Alba Gallo",
    responsabile: "Ing. Elena Fontana",
    note: "I raccordi sul design 3D non lasciano tolleranza per lo stampaggio."
  },
  {
    id: "nc-14",
    commessa: "COM-2658",
    cliente: "Brembo",
    codice_disegno: "DIS-2315-F",
    tipo_nc: "Interna",
    data_apertura: "2026-06-08",
    data_chiusura: "2026-06-09",
    reparto: "CNC",
    causa: "Errore di programmazione CAM",
    costo: 400.00,
    persona: "Davide Rossi",
    responsabile: "Ing. Giorgio Verdi",
    note: "Il file ISO finale conservava vecchie coordinate obsolete del percorso di svuotatura."
  }
];
